### ISSUE TITLE
there is some issue going on with some of the icons, they are not showing up. fix it

### ISSUE THREAD

**Issue by okieLoki** [developer-student-club-thapar/DSC-WebDev-Task#15]

**Comment by arnavgupta00** [comment]
**Icon issue fixed**
Import all assets.
```bash 
import locationIcon from './assets/images/location-icon.svg';
import websiteIcon from './assets/images/website-icon.svg';
import twitterIcon from './assets/images/twitter-icon.svg';
import companyIcon from './assets/images/company-icon.svg';
```
Then replace img src with Dynamic imports:
```bash 
<div className="bottom-icons">
   <img src={importName} />
</div>

```
**Instead of importName put Dynamic Name.**

**Comment by SmartKapila** [comment]
Please assign me this task

**Comment by okieLoki** [comment]
Assigned @SmartKapila

**Comment by SmartKapila** [comment]
Can you please advise a good website to get free svg images as I want to replace twitter svg with current logo of twitter in the src folder

**Comment by SmartKapila** [comment]
Solved the issue https://github.com/developer-student-club-thapar/DSC-WebDev-Task/pull/26#issue-1966705973
and created pull request #26 
Please merge that into main repository.

**Comment by okieLoki** [comment]
> Can you please advise a good website to get free svg images as I want to replace twitter svg with current logo of twitter in the src folder

use react icons (it almost every icon you would want)
