### ISSUE TITLE
the site is mobile first, so desktop view is not yet implemented, modify the css accordingly 

### ISSUE THREAD

**Issue by okieLoki** [developer-student-club-thapar/DSC-WebDev-Task#16]

**Comment by arnavgupta00** [comment]
I changed website to be desktop first and implemented mobile and tablet view via media queries 

1. For desktop view i made the container to be in center of screen.
2. Also i made dark and light mode functional with optimal color pallets
3. To cover up the empty space I made a upward-ball moving effect, it made made mainly in Javascript and CSS with 
    requirement to adding container div to html .
   
    ```bash 

    // Javascript 
    document.addEventListener("DOMContentLoaded", function () {
      const rainContainer = document.querySelector(".rain");
    
      for (let i = 0; i < 100; i++) {
        const drop = document.createElement("div");
        drop.className = "drop";
        drop.style.left = Math.random() * 100 + "vw";
        drop.style.animationDuration = Math.random() * 2 + 1 + "s";
        rainContainer.appendChild(drop);
      }
    });
    
   // CSS
   
   .rain {
      position: fixed;
      top: 100vh;
      left: 0;
      width: 100%;
      height: 100%;
      pointer-events: none;
      z-index: -1;
    }
    
    .drop {
      position: absolute;
      width: 5px;
      height: 5px;
      border-radius: 25px;
      background-color: var(--lm-text );
      animation: fall linear infinite;
    
    }
    
    @keyframes fall {
      to {
        transform: translateY(-100vh);
      }
    }
   // HTML
   <div class="rain"></div>
  
    
  ```

**Comment by arnavgupta00** [comment]
Here are some screen shots for better understanding:

![image](https://github.com/developer-student-club-thapar/DSC-WebDev-Task/assets/101815033/cfa102d7-916a-46e1-9729-b8d6fb45d46b)
![image](https://github.com/developer-student-club-thapar/DSC-WebDev-Task/assets/101815033/39d492b3-6f0f-4cb4-a5a2-9e84b42432e1)

**Comment by Harshika-Anand** [comment]
Please assign this issue to me

**Comment by genome07** [comment]
can I work on this issue?

**Comment by okieLoki** [comment]
@Harshika-Anand assigned

@genome07 since Harshika commented on this issue first, I assigned it to her, if you wish to contribute along with her I can assign you both with the same issue, or else you can look up for other issues.

**Comment by genome07** [comment]
@okieLoki oki I can contribute with her if possible

**Comment by okieLoki** [comment]
@Harshika-Anand @genome07 assigned to both of you
