### ISSUE TITLE
implement regUser function in userController

### ISSUE THREAD

**Issue by okieLoki** [developer-student-club-thapar/DSC-WebDev-Task#5]
Implement the regUser function in the userController to handle user registration. Ensure that user registration details are securely stored in the database. Validation of data is required (eg: email id should be thapar, phone number should be valid, etc.).

**Comment by kofta999** [comment]
Hello, I'd like to work on this issue, can I get more details on what basis should the data be validated?
Also should I manually validate or use packages like express-validator?

**Comment by okieLoki** [comment]
> Hello, I'd like to work on this issue, can I get more details on what basis should the data be validated? Also should I manually validate or use packages like express-validator?

Hi, just the basic email validation that it should be a thapar email ID and phone number should be 10 digits etc, etc. 

Also, it's up to you if you want to use express-validator or if you wish to do it manually.

**Comment by okieLoki** [comment]
@kofta999 assigned

**Comment by kofta999** [comment]
> > Hello, I'd like to work on this issue, can I get more details on what basis should the data be validated? Also should I manually validate or use packages like express-validator?
> 
> Hi, just the basic email validation that it should be a thapar email ID and phone number should be 10 digits etc, etc.
> 
> Also, it's up to you if you want to use express-validator or if you wish to do it manually.

understood, will work on it.
also just to be clear, a "thapar email ID" means an email that has the format "....@thapar.edu"?

**Comment by okieLoki** [comment]
> > > Hello, I'd like to work on this issue, can I get more details on what basis should the data be validated? Also should I manually validate or use packages like express-validator?
> > 
> > Hi, just the basic email validation that it should be a thapar email ID and phone number should be 10 digits etc, etc.
> > 
> > Also, it's up to you if you want to use express-validator or if you wish to do it manually.
> 
> understood, will work on it.
> also just to be clear, a "thapar email ID" means an email that has the format "....@thapar.edu"?

Yes

**Comment by okieLoki** [comment]
Good work @kofta999 :tada:

**Comment by kofta999** [comment]
tysmm
