### ISSUE TITLE
Implement getUser and getUsers end point

### ISSUE THREAD

**Issue by okieLoki** [developer-student-club-thapar/DSC-WebDev-Task#6]
Implement the getUser and getUsers functions in the userController to retrieve user information. getUser will retrieve information for a single user, and getUsers will retrieve a list of all users. Ensure that the data retrieval is done securely and efficiently. This end point is secured so only authenticated users can access it.

**Comment by kj-1809** [comment]
assign it to me.

**Comment by ParthKapoor-dev** [comment]
Can I work on this ?

**Comment by okieLoki** [comment]
Hii 

@kj-1809 since you already worked up on one issue, I assigned it to @ParthKapoor-dev 
However if you wish to contribute along with Parth, you can do so. I'll asign up the issue to both of you then
