### ISSUE TITLE
implement deleteUser end point

### ISSUE THREAD

**Issue by okieLoki** [developer-student-club-thapar/DSC-WebDev-Task#7]
Implement the deleteUser function in the userController to allow the deletion of user accounts. Ensure that the deletion process is secure and that the specified user's account is removed from the system.

**Comment by aman4uas** [comment]
Can you please assign this task to me.

**Comment by okieLoki** [comment]
@aman4uas assigned

**Comment by aman4uas** [comment]
Thanks @okieLoki !!

I will be raising PR latest by tomorrow.
